CREATE OR REPLACE PACKAGE MANAGE_BOOKS
AS
     PROCEDURE ADD_BOOK (I_BOOK_ID IN NUMBER, I_TITLE IN VARCHAR2, I_CATEGORY IN VARCHAR2, I_COST IN NUMBER);

     PROCEDURE REMOVE_BOOK (I_BOOK_ID IN NUMBER);

     PROCEDURE LIST_ALL_BOOKS(I_STATUS IN VARCHAR2);

     PROCEDURE UPDATE_BOOK_STATUS (I_BOOK_ID IN NUMBER, I_STATUS IN VARCHAR2);

     FUNCTION GET_BOOK_STATUS (I_BOOK_ID   IN   NUMBER)
      RETURN VARCHAR2;
END MANAGE_BOOKS;
.
/